const constructSkeletonColor = (start: string, middle: string, end: string) => [
	start,
	start,
	middle,
	middle,
	end,
	end,
];

export const themes = {
	dark: {
		'--primary': '#927AFF',
		'--secondary': '#6B4DBE',
		'--background': '#0F0F0F',
		'--light-background': '#1E1E1E',
		'--text': '#E8E8E8',
		'--selected': '#FFA726',
		'--card': '#1E1E1E',
		'--card-highlighted': '#322B50',
		'--static': '#FFFFFF',
		'--danger': '#D84343',
		'--shade': 'rgba(255, 255, 255, 0.35)',
		'--toast-bg': '#1A1A1A',
		'--toast-success': '#4CAF50',
		'--toast-error': '#E53935',
		'--toast-info': '#FF9800',
		skeleton: constructSkeletonColor('#252525', '#8066E0', '#252525'),
		'--bottomsheet-bg': '#1A1A1A',
	},
	light: {
		'--primary': '#5A3FBC',
		'--secondary': '#7F5ACC',
		'--background': '#FFFFFF',
		'--light-background': '#F6F6F6',
		'--selected': '#fb8610',
		'--text': '#212121',
		'--card': '#F0F0F5',
		'--card-highlighted': '#D6CFFA',
		'--static': '#ffffff',
		'--danger': '#D32F2F',
		'--shade': 'rgba(0, 0, 0, 0.4)',
		'--toast-bg': '#F5F5F5',
		'--toast-success': '#388E3C',
		'--toast-error': '#D32F2F',
		'--toast-info': '#1976D2',
		skeleton: constructSkeletonColor('#E0E0E0', '#7F5ACC', '#E0E0E0'),
		'--bottomsheet-bg': '#F0F0F0',
	},
};
export type ThemeStyle = (typeof themes)['dark'] | (typeof themes)['light'];
